package com.github.hypfvieh.javafx.fx.fonts;

public enum MapIcons implements IWebFontCode {

    MAP_ICON_ABSEILING                  ('\ue800'),
    MAP_ICON_ACCOUNTING                 ('\ue801'),
    MAP_ICON_AIRPORT                    ('\ue802'),
    MAP_ICON_AMUSEMENT_PARK             ('\ue803'),
    MAP_ICON_AQUARIUM                   ('\ue804'),
    MAP_ICON_ARCHERY                    ('\ue805'),
    MAP_ICON_ART_GALLERY                ('\ue806'),
    MAP_ICON_ASSISTIVE_LISTENING_SYSTEM ('\ue807'),
    MAP_ICON_ATM                        ('\ue808'),
    MAP_ICON_AUDIO_DESCRIPTION          ('\ue809'),
    MAP_ICON_BAKERY                     ('\ue80a'),
    MAP_ICON_BANK                       ('\ue80b'),
    MAP_ICON_BAR                        ('\ue80c'),
    MAP_ICON_BASEBALL                   ('\ue80d'),
    MAP_ICON_BEAUTY_SALON               ('\ue80e'),
    MAP_ICON_BICYCLE_STORE              ('\ue80f'),
    MAP_ICON_BICYCLING                  ('\ue810'),
    MAP_ICON_BOAT_RAMP                  ('\ue811'),
    MAP_ICON_BOAT_TOUR                  ('\ue812'),
    MAP_ICON_BOATING                    ('\ue813'),
    MAP_ICON_BOOK_STORE                 ('\ue814'),
    MAP_ICON_BOWLING_ALLEY              ('\ue815'),
    MAP_ICON_BRAILLE                    ('\ue816'),
    MAP_ICON_BUS_STATION                ('\ue817'),
    MAP_ICON_CAFE                       ('\ue818'),
    MAP_ICON_CAMPGROUND                 ('\ue819'),
    MAP_ICON_CANOE                      ('\ue81a'),
    MAP_ICON_CAR_DEALER                 ('\ue81b'),
    MAP_ICON_CAR_RENTAL                 ('\ue81c'),
    MAP_ICON_CAR_REPAIR                 ('\ue81d'),
    MAP_ICON_CAR_WASH                   ('\ue81e'),
    MAP_ICON_CASINO                     ('\ue81f'),
    MAP_ICON_CEMETERY                   ('\ue820'),
    MAP_ICON_CHAIRLIFT                  ('\ue821'),
    MAP_ICON_CHURCH                     ('\ue822'),
    MAP_ICON_CIRCLE                     ('\ue823'),
    MAP_ICON_CITY_HALL                  ('\ue824'),
    MAP_ICON_CLIMBING                   ('\ue825'),
    MAP_ICON_CLOSED_CAPTIONING          ('\ue826'),
    MAP_ICON_CLOTHING_STORE             ('\ue827'),
    MAP_ICON_COMPASS                    ('\ue828'),
    MAP_ICON_CONVENIENCE_STORE          ('\ue829'),
    MAP_ICON_COURTHOUSE                 ('\ue82a'),
    MAP_ICON_CROSS_COUNTRY_SKIING       ('\ue82b'),
    MAP_ICON_CROSSHAIRS                 ('\ue82c'),
    MAP_ICON_DENTIST                    ('\ue82d'),
    MAP_ICON_DEPARTMENT_STORE           ('\ue82e'),
    MAP_ICON_DIVING                     ('\ue82f'),
    MAP_ICON_DOCTOR                     ('\ue830'),
    MAP_ICON_ELECTRICIAN                ('\ue831'),
    MAP_ICON_ELECTRONICS_STORE          ('\ue832'),
    MAP_ICON_EMBASSY                    ('\ue833'),
    MAP_ICON_EXPAND                     ('\ue834'),
    MAP_ICON_FEMALE                     ('\ue835'),
    MAP_ICON_FINANCE                    ('\ue836'),
    MAP_ICON_FIRE_STATION               ('\ue837'),
    MAP_ICON_FISH_CLEANING              ('\ue838'),
    MAP_ICON_FISHING_PIER               ('\ue839'),
    MAP_ICON_FISHING                    ('\ue83a'),
    MAP_ICON_FLORIST                    ('\ue83b'),
    MAP_ICON_FOOD                       ('\ue83c'),
    MAP_ICON_FULLSCREEN                 ('\ue83d'),
    MAP_ICON_FUNERAL_HOME               ('\ue83e'),
    MAP_ICON_FURNITURE_STORE            ('\ue83f'),
    MAP_ICON_GAS_STATION                ('\ue840'),
    MAP_ICON_GENERAL_CONTRACTOR         ('\ue841'),
    MAP_ICON_GOLF                       ('\ue842'),
    MAP_ICON_GROCERY_OR_SUPERMARKET     ('\ue843'),
    MAP_ICON_GYM                        ('\ue844'),
    MAP_ICON_HAIR_CARE                  ('\ue845'),
    MAP_ICON_HANG_GLIDING               ('\ue846'),
    MAP_ICON_HARDWARE_STORE             ('\ue847'),
    MAP_ICON_HEALTH                     ('\ue848'),
    MAP_ICON_HINDU_TEMPLE               ('\ue849'),
    MAP_ICON_HORSE_RIDING               ('\ue84a'),
    MAP_ICON_HOSPITAL                   ('\ue84b'),
    MAP_ICON_ICE_FISHING                ('\ue84c'),
    MAP_ICON_ICE_SKATING                ('\ue84d'),
    MAP_ICON_INLINE_SKATING             ('\ue84e'),
    MAP_ICON_INSURANCE_AGENCY           ('\ue84f'),
    MAP_ICON_JET_SKIING                 ('\ue850'),
    MAP_ICON_JEWELRY_STORE              ('\ue851'),
    MAP_ICON_KAYAKING                   ('\ue852'),
    MAP_ICON_LAUNDRY                    ('\ue853'),
    MAP_ICON_LAWYER                     ('\ue854'),
    MAP_ICON_LIBRARY                    ('\ue855'),
    MAP_ICON_LIQUOR_STORE               ('\ue856'),
    MAP_ICON_LOCAL_GOVERNMENT           ('\ue857'),
    MAP_ICON_LOCATION_ARROW             ('\ue858'),
    MAP_ICON_LOCKSMITH                  ('\ue859'),
    MAP_ICON_LODGING                    ('\ue85a'),
    MAP_ICON_LOW_VISION_ACCESS          ('\ue85b'),
    MAP_ICON_MALE                       ('\ue85c'),
    MAP_ICON_MAP_PIN                    ('\ue85d'),
    MAP_ICON_MARINA                     ('\ue85e'),
    MAP_ICON_MOSQUE                     ('\ue85f'),
    MAP_ICON_MOTOBIKE_TRAIL             ('\ue860'),
    MAP_ICON_MOVIE_RENTAL               ('\ue861'),
    MAP_ICON_MOVIE_THEATER              ('\ue862'),
    MAP_ICON_MOVING_COMPANY             ('\ue863'),
    MAP_ICON_MUSEUM                     ('\ue864'),
    MAP_ICON_NATURAL_FEATURE            ('\ue865'),
    MAP_ICON_NIGHT_CLUB                 ('\ue866'),
    MAP_ICON_OPEN_CAPTIONING            ('\ue867'),
    MAP_ICON_PAINTER                    ('\ue868'),
    MAP_ICON_PARK                       ('\ue869'),
    MAP_ICON_PARKING                    ('\ue86a'),
    MAP_ICON_PET_STORE                  ('\ue86b'),
    MAP_ICON_PHARMACY                   ('\ue86c'),
    MAP_ICON_PHYSIOTHERAPIST            ('\ue86d'),
    MAP_ICON_PLACE_OF_WORSHIP           ('\ue86e'),
    MAP_ICON_PLAYGROUND                 ('\ue86f'),
    MAP_ICON_PLUMBER                    ('\ue870'),
    MAP_ICON_POINT_OF_INTEREST          ('\ue871'),
    MAP_ICON_POLICE                     ('\ue872'),
    MAP_ICON_POLITICAL                  ('\ue873'),
    MAP_ICON_POST_BOX                   ('\ue874'),
    MAP_ICON_POST_OFFICE                ('\ue875'),
    MAP_ICON_POSTAL_CODE_PREFIX         ('\ue876'),
    MAP_ICON_POSTAL_CODE                ('\ue877'),
    MAP_ICON_RAFTING                    ('\ue878'),
    MAP_ICON_REAL_ESTATE_AGENCY         ('\ue879'),
    MAP_ICON_RESTAURANT                 ('\ue87a'),
    MAP_ICON_ROOFING_CONTRACTOR         ('\ue87b'),
    MAP_ICON_ROUTE_PIN                  ('\ue87c'),
    MAP_ICON_ROUTE                      ('\ue87d'),
    MAP_ICON_RV_PARK                    ('\ue87e'),
    MAP_ICON_SAILING                    ('\ue87f'),
    MAP_ICON_SCHOOL                     ('\ue880'),
    MAP_ICON_SCUBA_DIVING               ('\ue881'),
    MAP_ICON_SEARCH                     ('\ue882'),
    MAP_ICON_SHIELD                     ('\ue883'),
    MAP_ICON_SHOPPING_MALL              ('\ue884'),
    MAP_ICON_SIGN_LANGUAGE              ('\ue885'),
    MAP_ICON_SKATEBOARDING              ('\ue886'),
    MAP_ICON_SKI_JUMPING                ('\ue887'),
    MAP_ICON_SKIING                     ('\ue888'),
    MAP_ICON_SLEDDING                   ('\ue889'),
    MAP_ICON_SNOW_SHOEING               ('\ue88a'),
    MAP_ICON_SNOW                       ('\ue88b'),
    MAP_ICON_SNOWBOARDING               ('\ue88c'),
    MAP_ICON_SNOWMOBILE                 ('\ue88d'),
    MAP_ICON_SPA                        ('\ue88e'),
    MAP_ICON_SQUARE_PIN                 ('\ue88f'),
    MAP_ICON_SQUARE_ROUNDED             ('\ue890'),
    MAP_ICON_SQUARE                     ('\ue891'),
    MAP_ICON_STADIUM                    ('\ue892'),
    MAP_ICON_STORAGE                    ('\ue893'),
    MAP_ICON_STORE                      ('\ue894'),
    MAP_ICON_SUBWAY_STATION             ('\ue895'),
    MAP_ICON_SURFING                    ('\ue896'),
    MAP_ICON_SWIMMING                   ('\ue897'),
    MAP_ICON_SYNAGOGUE                  ('\ue898'),
    MAP_ICON_TAXI_STAND                 ('\ue899'),
    MAP_ICON_TENNIS                     ('\ue89a'),
    MAP_ICON_TOILET                     ('\ue89b'),
    MAP_ICON_TRAIL_WALKING              ('\ue89c'),
    MAP_ICON_TRAIN_STATION              ('\ue89d'),
    MAP_ICON_TRANSIT_STATION            ('\ue89e'),
    MAP_ICON_TRAVEL_AGENCY              ('\ue89f'),
    MAP_ICON_UNISEX                     ('\ue8a0'),
    MAP_ICON_UNIVERSITY                 ('\ue8a1'),
    MAP_ICON_VETERINARY_CARE            ('\ue8a2'),
    MAP_ICON_VIEWING                    ('\ue8a3'),
    MAP_ICON_VOLUME_CONTROL_TELEPHONE   ('\ue8a4'),
    MAP_ICON_WALKING                    ('\ue8a5'),
    MAP_ICON_WATERSKIING                ('\ue8a6'),
    MAP_ICON_WHALE_WATCHING             ('\ue8a7'),
    MAP_ICON_WHEELCHAIR                 ('\ue8a8'),
    MAP_ICON_WIND_SURFING               ('\ue8a9'),
    MAP_ICON_ZOO                        ('\ue8aa'),
    MAP_ICON_ZOOM_IN_ALT                ('\ue8ab'),
    MAP_ICON_ZOOM_IN                    ('\ue8ac'),
    MAP_ICON_ZOOM_OUT_ALT               ('\ue8ad'),
    MAP_ICON_ZOOM_OUT                   ('\ue8ae');

    private final Character character;

    private MapIcons(Character _character) {
        character = _character;
    }

    @Override
    public Character getCharacter() {
        return character;
    }

    @Override
    public String getFontFamily() {
        return "map-icons;";
    }

}

