package com.github.hypfvieh.javafx.fx.fonts;

public enum MfgIconSet implements IWebFontCode {

    ICON_AT                   ('\u0040'),
    ICON_PLUS                 ('\u002B'),
    ICON_MINUS                ('\u2212'),
    ICON_ARROW_UP             ('\u2191'),
    ICON_ARROW_DOWN           ('\u2193'),
    ICON_ARROW_RIGHT          ('\u2192'),
    ICON_ARROW_LEFT           ('\u2190'),
    ICON_CHEVRON_DOWN         ('\uf004'),
    ICON_CHEVRON_UP           ('\uf005'),
    ICON_CHEVRON_RIGHT        ('\uf006'),
    ICON_CHEVRON_LEFT         ('\uf007'),
    ICON_REORDER              ('\uf008'),
    ICON_LIST                 ('\uf009'),
    ICON_REORDER_SQUARE       ('\uf00a'),
    ICON_REORDER_SQUARE_LINE  ('\uf00b'),
    ICON_COVERFLOW            ('\uf00c'),
    ICON_COVERFLOW_LINE       ('\uf00d'),
    ICON_PAUSE                ('\uf00e'),
    ICON_PLAY                 ('\uf00f'),
    ICON_STEP_FORWARD         ('\uf010'),
    ICON_STEP_BACKWARD        ('\uf011'),
    ICON_FAST_FORWARD         ('\uf012'),
    ICON_FAST_BACKWARD        ('\uf013'),
    ICON_CLOUD_UPLOAD         ('\uf014'),
    ICON_CLOUD_DOWNLOAD       ('\uf015'),
    ICON_DATA_SCIENCE         ('\uf016'),
    ICON_DATA_SCIENCE_BLACK   ('\uf017'),
    ICON_GLOBE                ('\uf018'),
    ICON_GLOBE_BLACK          ('\uf019'),
    ICON_MATH_ICO             ('\uf01a'),
    ICON_MATH                 ('\uf01b'),
    ICON_MATH_BLACK           ('\uf01c'),
    ICON_PAPERPLANE_ICO       ('\uf01d'),
    ICON_PAPERPLANE           ('\uf01e'),
    ICON_PAPERPLANE_BLACK     ('\uf01f'),
    ICON_STAR                 ('\u2605'),
    ICON_STAR_HALF            ('\uf022'),
    ICON_STAR_EMPTY           ('\u2606'),
    ICON_STAR_HALF_EMPTY      ('\uf024'),
    ICON_RELOAD               ('\uf025'),
    ICON_HEART                ('\u2665'),
    ICON_HEART_BROKEN         ('\uf028'),
    ICON_HASHTAG              ('\uf029'),
    ICON_REPLY                ('\uf02a'),
    ICON_RETWEET              ('\uf02b'),
    ICON_SIGNIN               ('\uf02c'),
    ICON_SIGNOUT              ('\uf02d'),
    ICON_DOWNLOAD             ('\uf02e'),
    ICON_UPLOAD               ('\uf02f'),
    ICON_PLACEPIN             ('\uf031'),
    ICON_DISPLAY_SCREEN       ('\uf032'),
    ICON_TABLET               ('\uf033'),
    ICON_SMARTPHONE           ('\uf034'),
    ICON_CONNECTED_OBJECT     ('\uf035'),
    ICON_LOCK                 ('\uF512'),
    ICON_UNLOCK               ('\uF513'),
    ICON_CAMERA               ('\uF4F7'),
    ICON_ISIGHT               ('\uf039'),
    ICON_VIDEO_CAMERA         ('\uf03a'),
    ICON_RANDOM               ('\uf03b'),
    ICON_MESSAGE              ('\uF4AC'),
    ICON_DISCUSSION           ('\uf03d'),
    ICON_CALENDAR             ('\uF4C5'),
    ICON_RINGBELL             ('\uf03f'),
    ICON_MOVIE                ('\uf040'),
    ICON_MAIL                 ('\u2709'),
    ICON_PEN                  ('\u270F'),
    ICON_SETTINGS             ('\u9881'),
    ICON_MEASURE              ('\uf044'),
    ICON_VECTOR               ('\uf045'),
    ICON_VECTOR_PEN           ('\u2712'),
    ICON_MUTE_ON              ('\uf047'),
    ICON_MUTE_OFF             ('\uf048'),
    ICON_HOME                 ('\u2302'),
    ICON_SHEET                ('\uf04a'),
    ICON_ARROW_BIG_RIGHT      ('\u21C9'),
    ICON_ARROW_BIG_LEFT       ('\u21C7'),
    ICON_ARROW_BIG_DOWN       ('\u21CA'),
    ICON_ARROW_BIG_UP         ('\u21C8'),
    ICON_DRIBBBLE_CIRCLE      ('\uf04f'),
    ICON_DRIBBBLE             ('\uf050'),
    ICON_FACEBOOK_CIRCLE      ('\uf051'),
    ICON_FACEBOOK             ('\uf052'),
    ICON_GIT_CIRCLE_ALT       ('\uf053'),
    ICON_GIT_CIRCLE           ('\uf054'),
    ICON_GIT                  ('\uf055'),
    ICON_OCTOPUS              ('\uf056'),
    ICON_TWITTER_CIRCLE       ('\uf057'),
    ICON_TWITTER              ('\uf058'),
    ICON_GOOGLE_PLUS_CIRCLE   ('\uf059'),
    ICON_GOOGLE_PLUS          ('\uf05a'),
    ICON_LINKED_IN_CIRCLE     ('\uf05b'),
    ICON_LINKED_IN            ('\uf05c'),
    ICON_INSTAGRAM            ('\uf05d'),
    ICON_INSTAGRAM_CIRCLE     ('\uf05e'),
    ICON_MFG_ICON             ('\uf05f'),
    ICON_XING                 ('\uF532'),
    ICON_XING_CIRCLE          ('\uF533'),
    ICON_MFG_ICON_CIRCLE      ('\uf060'),
    ICON_USER                 ('\uf061'),
    ICON_USER_MALE            ('\uf062'),
    ICON_USER_FEMALE          ('\uf063'),
    ICON_USERS                ('\uf064'),
    ICON_FILE_OPEN            ('\uF4C2'),
    ICON_FILE_CLOSE           ('\uf067'),
    ICON_FILE_ALT             ('\uf068'),
    ICON_FILE_CLOSE_ALT       ('\uf069'),
    ICON_ATTACHMENT           ('\uf06a'),
    ICON_CHECK                ('\u2713'),
    ICON_CROSS_MARK           ('\u274C'),
    ICON_CANCEL_CIRCLE        ('\uF06E'),
    ICON_CHECK_CIRCLE         ('\uf06d'),
    ICON_MAGNIFYING           ('\uF50D'),
    ICON_INBOX                ('\uf070'),
    ICON_CLOCK                ('\u23F2'),
    ICON_STOPWATCH            ('\u23F1'),
    ICON_HOURGLASS            ('\u231B'),
    ICON_TROPHY               ('\uf074'),
    ICON_UNLOCK_ALT           ('\uF075'),
    ICON_LOCK_ALT             ('\uF510'),
    ICON_ARROW_DOUBLED_RIGHT  ('\u21D2'),
    ICON_ARROW_DOUBLED_LEFT   ('\u21D0'),
    ICON_ARROW_DOUBLED_DOWN   ('\u21D3'),
    ICON_ARROW_DOUBLED_UP     ('\u21D1'),
    ICON_LINK                 ('\uf07B'),
    ICON_WARNING              ('\u2757'),
    ICON_WARNING_ALT          ('\u2755'),
    ICON_MAGNIFYING_PLUS      ('\uf07E'),
    ICON_MAGNIFYING_MINUS     ('\uf07F'),
    ICON_WHITE_QUESTION       ('\u2754'),
    ICON_BLACK_QUESTION       ('\u2753'),
    ICON_STOP                 ('\uf080'),
    ICON_SHARE                ('\uf081'),
    ICON_EYE                  ('\uf082'),
    ICON_TRASH_CAN            ('\uf083'),
    ICON_HARD_DRIVE           ('\uf084'),
    ICON_INFORMATION_BLACK    ('\uf085'),
    ICON_INFORMATION_WHITE    ('\uf086'),
    ICON_PRINTER              ('\uf087'),
    ICON_LETTER               ('\uf088'),
    ICON_SOUNDCLOUD           ('\uf089'),
    ICON_SOUNDCLOUD_CIRCLE    ('\uf08A'),
    ICON_ANCHOR               ('\u2693'),
    ICON_FEMALE_SIGN          ('\u2640'),
    ICON_MALE_SIGN            ('\u2642'),
    ICON_JOYSTICK             ('\uF514'),
    ICON_HIGH_VOLTAGE         ('\u26A1'),
    ICON_FIRE                 ('\uF525'),
    ICON_NEWSPAPER            ('\uF4F0'),
    ICON_CHART                ('\uF526'),
    ICON_SPREAD               ('\uF527'),
    ICON_SPINNER_1            ('\uF528'),
    ICON_SPINNER_2            ('\uF529'),
    ICON_CHART_ALT            ('\uF530'),
    ICON_LABEL                ('\uF531'),
    ICON_BRUSH                ('\uE000'),
    ICON_REFRESH              ('\uE001'),
    ICON_NODE                 ('\uE002'),
    ICON_NODE_2               ('\uE003'),
    ICON_NODE_3               ('\uE004'),
    ICON_LINK_2_NODES         ('\uE005'),
    ICON_LINK_3_NODES         ('\uE006'),
    ICON_LINK_LOOP_NODES      ('\uE007'),
    ICON_NODE_SIZE            ('\uE008'),
    ICON_NODE_COLOR           ('\uE009'),
    ICON_LAYOUT_DIRECTED      ('\uE010'),
    ICON_LAYOUT_RADIAL        ('\uE011'),
    ICON_LAYOUT_HIERARCHICAL  ('\uE012'),
    ICON_NODE_LINK_DIRECTION  ('\uE013'),
    ICON_NODE_LINK_SHORT_PATH ('\uE014'),
    ICON_NODE_CLUSTER         ('\uE015'),
    ICON_DISPLAY_GRAPH        ('\uE016'),
    ICON_NODE_LINK_WEIGHT     ('\uE017'),
    ICON_MORE_NODE_LINKS      ('\uE018'),
    ICON_NODE_SHAPE           ('\uE00A'),
    ICON_NODE_ICON            ('\uE00B'),
    ICON_NODE_TEXT            ('\uE00C'),
    ICON_NODE_LINK_TEXT       ('\uE00D'),
    ICON_NODE_LINK_COLOR      ('\uE00E'),
    ICON_NODE_LINK_SHAPE      ('\uE00F'),
    ICON_CREDIT_CARD          ('\uF4B3'),
    ICON_DISCONNECT           ('\uF534'),
    ICON_GRAPH                ('\uF535'),
    ICON_NEW_USER             ('\uF536');

    private final Character character;

    private MfgIconSet(Character _character) {
        character = _character;
    }

    @Override
    public Character getCharacter() {
        return character;
    }

    @Override
    public String getFontFamily() {
        return "mfg_labs_iconsetregular";
    }

}

