package com.github.hypfvieh.javafx.fx.fonts;

public enum MFizz implements IWebFontCode {

    ICON_3DPRINT                ('\uf100'),
    ICON_ALPINELINUX            ('\uf101'),
    ICON_ANGULAR                ('\uf102'),
    ICON_ANGULAR_ALT            ('\uf103'),
    ICON_ANTENNA                ('\uf104'),
    ICON_APACHE                 ('\uf105'),
    ICON_ARCHLINUX              ('\uf106'),
    ICON_AWS                    ('\uf107'),
    ICON_AZURE                  ('\uf108'),
    ICON_BACKBONE               ('\uf109'),
    ICON_BLACKBERRY             ('\uf10a'),
    ICON_BOMB                   ('\uf10b'),
    ICON_BOOTSTRAP              ('\uf10c'),
    ICON_C                      ('\uf10d'),
    ICON_CASSANDRA              ('\uf10e'),
    ICON_CENTOS                 ('\uf10f'),
    ICON_CLOJURE                ('\uf110'),
    ICON_CODEIGNITER            ('\uf111'),
    ICON_CODEPEN                ('\uf112'),
    ICON_COFFEE_BEAN            ('\uf113'),
    ICON_CPLUSPLUS              ('\uf114'),
    ICON_CSHARP                 ('\uf115'),
    ICON_CSS                    ('\uf116'),
    ICON_CSS3                   ('\uf117'),
    ICON_CSS3_ALT               ('\uf118'),
    ICON_D3                     ('\uf119'),
    ICON_DATABASE               ('\uf11a'),
    ICON_DATABASE_ALT           ('\uf11b'),
    ICON_DATABASE_ALT2          ('\uf11c'),
    ICON_DEBIAN                 ('\uf11d'),
    ICON_DOCKER                 ('\uf11e'),
    ICON_DREAMHOST              ('\uf11f'),
    ICON_ELIXIR                 ('\uf120'),
    ICON_ELM                    ('\uf121'),
    ICON_ERLANG                 ('\uf122'),
    ICON_EXHERBO                ('\uf123'),
    ICON_FEDORA                 ('\uf124'),
    ICON_FIRE_ALT               ('\uf125'),
    ICON_FREEBSD                ('\uf126'),
    ICON_FREECODECAMP           ('\uf127'),
    ICON_GENTOO                 ('\uf128'),
    ICON_GHOST                  ('\uf129'),
    ICON_GIT                    ('\uf12a'),
    ICON_GNOME                  ('\uf12b'),
    ICON_GO                     ('\uf12c'),
    ICON_GO_ALT                 ('\uf12d'),
    ICON_GOOGLE                 ('\uf12e'),
    ICON_GOOGLE_ALT             ('\uf12f'),
    ICON_GOOGLE_CODE            ('\uf130'),
    ICON_GOOGLE_DEVELOPERS      ('\uf131'),
    ICON_GRADLE                 ('\uf132'),
    ICON_GRAILS                 ('\uf133'),
    ICON_GRAILS_ALT             ('\uf134'),
    ICON_GRUNT                  ('\uf135'),
    ICON_GULP                   ('\uf136'),
    ICON_GULP_ALT               ('\uf137'),
    ICON_HADOOP                 ('\uf138'),
    ICON_HASKELL                ('\uf139'),
    ICON_HEROKU                 ('\uf13a'),
    ICON_HTML                   ('\uf13b'),
    ICON_HTML5                  ('\uf13c'),
    ICON_HTML5_ALT              ('\uf13d'),
    ICON_IPHONE                 ('\uf13e'),
    ICON_JAVA                   ('\uf13f'),
    ICON_JAVA_BOLD              ('\uf140'),
    ICON_JAVA_DUKE              ('\uf141'),
    ICON_JAVASCRIPT             ('\uf142'),
    ICON_JAVASCRIPT_ALT         ('\uf143'),
    ICON_JETTY                  ('\uf144'),
    ICON_JQUERY                 ('\uf145'),
    ICON_KDE                    ('\uf146'),
    ICON_LARAVEL                ('\uf147'),
    ICON_LINE_GRAPH             ('\uf148'),
    ICON_LINUX_MINT             ('\uf149'),
    ICON_LOOKING                ('\uf14a'),
    ICON_MAGENTO                ('\uf14b'),
    ICON_MARIADB                ('\uf14c'),
    ICON_MAVEN                  ('\uf14d'),
    ICON_MICROSCOPE             ('\uf14e'),
    ICON_MOBILE_DEVICE          ('\uf14f'),
    ICON_MOBILE_PHONE_ALT       ('\uf150'),
    ICON_MOBILE_PHONE_BROADCAST ('\uf151'),
    ICON_MONGODB                ('\uf152'),
    ICON_MSSQL                  ('\uf153'),
    ICON_MYSQL                  ('\uf154'),
    ICON_MYSQL_ALT              ('\uf155'),
    ICON_NETBSD                 ('\uf156'),
    ICON_NGINX                  ('\uf157'),
    ICON_NGINX_ALT              ('\uf158'),
    ICON_NGINX_ALT2             ('\uf159'),
    ICON_NODEJS                 ('\uf15a'),
    ICON_NPM                    ('\uf15b'),
    ICON_OBJC                   ('\uf15c'),
    ICON_OPENSHIFT              ('\uf15d'),
    ICON_ORACLE                 ('\uf15e'),
    ICON_ORACLE_ALT             ('\uf15f'),
    ICON_OSX                    ('\uf160'),
    ICON_PERL                   ('\uf161'),
    ICON_PHONE_ALT              ('\uf162'),
    ICON_PHONE_GAP              ('\uf163'),
    ICON_PHONE_RETRO            ('\uf164'),
    ICON_PHP                    ('\uf165'),
    ICON_PHP_ALT                ('\uf166'),
    ICON_PLAYFRAMEWORK          ('\uf167'),
    ICON_PLAYFRAMEWORK_ALT      ('\uf168'),
    ICON_PLONE                  ('\uf169'),
    ICON_POSTGRES               ('\uf16a'),
    ICON_POSTGRES_ALT           ('\uf16b'),
    ICON_PYTHON                 ('\uf16c'),
    ICON_RASPBERRYPI            ('\uf16d'),
    ICON_REACTJS                ('\uf16e'),
    ICON_REDHAT                 ('\uf16f'),
    ICON_REDIS                  ('\uf170'),
    ICON_RUBY                   ('\uf171'),
    ICON_RUBY_ON_RAILS          ('\uf172'),
    ICON_RUBY_ON_RAILS_ALT      ('\uf173'),
    ICON_RUST                   ('\uf174'),
    ICON_SASS                   ('\uf175'),
    ICON_SATELLITE              ('\uf176'),
    ICON_SCALA                  ('\uf177'),
    ICON_SCALA_ALT              ('\uf178'),
    ICON_SCRIPT                 ('\uf179'),
    ICON_SCRIPT_ALT             ('\uf17a'),
    ICON_SHELL                  ('\uf17b'),
    ICON_SITEFINITY             ('\uf17c'),
    ICON_SOLARIS                ('\uf17d'),
    ICON_SPLATTER               ('\uf17e'),
    ICON_SPRING                 ('\uf17f'),
    ICON_SUSE                   ('\uf180'),
    ICON_SVG                    ('\uf181'),
    ICON_SYMFONY                ('\uf182'),
    ICON_TOMCAT                 ('\uf183'),
    ICON_UBUNTU                 ('\uf184'),
    ICON_UNITY                  ('\uf185'),
    ICON_WIRELESS               ('\uf186'),
    ICON_WORDPRESS              ('\uf187'),
    ICON_X11                    ('\uf188');

    private final Character character;

    private MFizz(Character _character) {
        character = _character;
    }

    @Override
    public Character getCharacter() {
        return character;
    }

    @Override
    public String getFontFamily() {
        return "FontMfizz;";
    }

}

