package com.github.hypfvieh.javafx.fx.fonts;

public enum Zocial implements IWebFontCode {

    ZOCIALAMAZON            ('\uf101'),
    ZOCIALANDROID           ('\uf102'),
    ZOCIALANGELLIST         ('\uf103'),
    ZOCIALAOL               ('\uf104'),
    ZOCIALAPPNET            ('\uf105'),
    ZOCIALAPPSTORE          ('\uf106'),
    ZOCIALASKFM             ('\uf107'),
    ZOCIALBETASERIES        ('\uf108'),
    ZOCIALBITBUCKET         ('\uf109'),
    ZOCIALBITCOIN           ('\uf10a'),
    ZOCIALBLOGGER           ('\uf10b'),
    ZOCIALBUFFER            ('\uf10c'),
    ZOCIALCAL               ('\uf10d'),
    ZOCIALCALL              ('\uf10e'),
    ZOCIALCART              ('\uf10f'),
    ZOCIALCHROME            ('\uf110'),
    ZOCIALCLOUDAPP          ('\uf111'),
    ZOCIALCREATIVECOMMONS   ('\uf112'),
    ZOCIALDELICIOUS         ('\uf113'),
    ZOCIALDEVIANTART        ('\uf114'),
    ZOCIALDIGG              ('\uf115'),
    ZOCIALDISCORDAPP        ('\uf116'),
    ZOCIALDISQUS            ('\uf117'),
    ZOCIALDRIBBBLE          ('\uf118'),
    ZOCIALDROPBOX           ('\uf119'),
    ZOCIALDRUPAL            ('\uf11a'),
    ZOCIALDWOLLA            ('\uf11b'),
    ZOCIALEMAIL             ('\uf11c'),
    ZOCIALEVENTASAURUS      ('\uf11d'),
    ZOCIALEVENTBRITE        ('\uf11e'),
    ZOCIALEVENTFUL          ('\uf11f'),
    ZOCIALEVERNOTE          ('\uf120'),
    ZOCIALFACEBOOK          ('\uf121'),
    ZOCIALFIVEHUNDREDPX     ('\uf122'),
    ZOCIALFLATTR            ('\uf123'),
    ZOCIALFLICKR            ('\uf124'),
    ZOCIALFORRST            ('\uf125'),
    ZOCIALFOURSQUARE        ('\uf126'),
    ZOCIALGITHUB            ('\uf127'),
    ZOCIALGITLAB            ('\uf128'),
    ZOCIALGMAIL             ('\uf129'),
    ZOCIALGOOGLE            ('\uf12a'),
    ZOCIALGOOGLEPLAY        ('\uf12b'),
    ZOCIALGOOGLEPLUS        ('\uf12c'),
    ZOCIALGOWALLA           ('\uf12d'),
    ZOCIALGROOVESHARK       ('\uf12e'),
    ZOCIALGUEST             ('\uf12f'),
    ZOCIALHOUZZ             ('\uf130'),
    ZOCIALHTML5             ('\uf131'),
    ZOCIALIE                ('\uf132'),
    ZOCIALINSTAGRAM         ('\uf133'),
    ZOCIALINSTAPAPER        ('\uf134'),
    ZOCIALINTENSEDEBATE     ('\uf135'),
    ZOCIALITUNES            ('\uf136'),
    ZOCIALJOINME            ('\uf137'),
    ZOCIALKLOUT             ('\uf138'),
    ZOCIALLANYRD            ('\uf139'),
    ZOCIALLASTFM            ('\uf13a'),
    ZOCIALLEGO              ('\uf13b'),
    ZOCIALLINKEDIN          ('\uf13c'),
    ZOCIALLKDTO             ('\uf13d'),
    ZOCIALLOGMEIN           ('\uf13e'),
    ZOCIALMACSTORE          ('\uf13f'),
    ZOCIALMEETUP            ('\uf140'),
    ZOCIALMYSPACE           ('\uf141'),
    ZOCIALNINETYNINEDESIGNS ('\uf142'),
    ZOCIALOPENID            ('\uf143'),
    ZOCIALOPENTABLE         ('\uf144'),
    ZOCIALPANDORA           ('\uf16e'),
    ZOCIALPAYPAL            ('\uf145'),
    ZOCIALPERSONA           ('\uf146'),
    ZOCIALPINBOARD          ('\uf147'),
    ZOCIALPINTEREST         ('\uf148'),
    ZOCIALPLANCAST          ('\uf149'),
    ZOCIALPLURK             ('\uf14a'),
    ZOCIALPOCKET            ('\uf14b'),
    ZOCIALPODCAST           ('\uf14c'),
    ZOCIALPOSTEROUS         ('\uf14d'),
    ZOCIALPRINT             ('\uf14e'),
    ZOCIALQUORA             ('\uf14f'),
    ZOCIALREDDIT            ('\uf150'),
    ZOCIALRSS               ('\uf151'),
    ZOCIALSCRIBD            ('\uf152'),
    ZOCIALSKYPE             ('\uf153'),
    ZOCIALSLACK             ('\uf154'),
    ZOCIALSMASHING          ('\uf155'),
    ZOCIALSONGKICK          ('\uf156'),
    ZOCIALSOUNDCLOUD        ('\uf157'),
    ZOCIALSPOTIFY           ('\uf158'),
    ZOCIALSTACKOVERFLOW     ('\uf159'),
    ZOCIALSTATUSNET         ('\uf15a'),
    ZOCIALSTEAM             ('\uf15b'),
    ZOCIALSTRIPE            ('\uf15c'),
    ZOCIALSTUMBLEUPON       ('\uf15d'),
    ZOCIALTUMBLR            ('\uf15e'),
    ZOCIALTWITCH            ('\uf15f'),
    ZOCIALTWITTER           ('\uf160'),
    ZOCIALVIADEO            ('\uf161'),
    ZOCIALVIMEO             ('\uf162'),
    ZOCIALVK                ('\uf163'),
    ZOCIALWEIBO             ('\uf164'),
    ZOCIALWIKIPEDIA         ('\uf165'),
    ZOCIALWINDOWS           ('\uf166'),
    ZOCIALWORDPRESS         ('\uf167'),
    ZOCIALWWW               ('\uf168'),
    ZOCIALXING              ('\uf169'),
    ZOCIALYAHOO             ('\uf16a'),
    ZOCIALYCOMBINATOR       ('\uf16b'),
    ZOCIALYELP              ('\uf16c'),
    ZOCIALYOUTUBE           ('\uf16d');

    private final Character character;

    private Zocial(Character _character) {
        character = _character;
    }

    @Override
    public Character getCharacter() {
        return character;
    }

    @Override
    public String getFontFamily() {
        return "zocial";
    }

}

